"""Export Beast Mode playbooks to markdown, plain text, HTML, and PDF."""
from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from io import BytesIO
from textwrap import wrap
from typing import Any, Dict, Iterable, List, Mapping, Sequence


def _ascii_safe(text: Any) -> str:
    value = str(text or "")
    return value.encode("ascii", errors="replace").decode("ascii")


def _lines(title: str, rows: Sequence[Mapping[str, Any]], columns: Sequence[str]) -> List[str]:
    output = [title]
    if not rows:
        output.append("  (none)")
        return output
    for row in rows:
        parts = [f"{column}: {row.get(column, '')}" for column in columns if column in row]
        output.append("  - " + " | ".join(_ascii_safe(part) for part in parts))
    return output


def format_playbook_markdown(report: Mapping[str, Any], *, profile_name: str = "") -> str:
    blueprint = report.get("blueprint") or {}
    beast = blueprint.get("beast") or {}
    lines: List[str] = [
        f"# Beast Mode Playbook — {report.get('label', 'Build')}",
        "",
        f"Profile: {profile_name or 'Tower Optimizer profile'}",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        f"**Tagline:** {report.get('tagline', '')}",
        f"**Build fit:** {report.get('fit_score', '—')}/100 ({report.get('fit_label', '')})",
        f"**Readiness:** {blueprint.get('readiness_score', '—')}/100",
        f"**Latest death:** {report.get('latest_death', 'No report saved')}",
        "",
        "## Master checklist",
    ]
    checklist = blueprint.get("master_checklist") or []
    if checklist:
        for index, row in enumerate(checklist, start=1):
            lines.append(
                f"{index}. [{row.get('Priority')}] **{row.get('Action')}** ({row.get('System')}) — {row.get('Why', '')}"
            )
    else:
        lines.append("- No checklist items generated.")

    death = beast.get("death") or {}
    if death.get("matched"):
        lines.extend(["", "## Death tweak", f"**{death.get('matched')}:** {death.get('summary', '')}"])
        if death.get("add_cards"):
            lines.append(f"- Add cards: {', '.join(death['add_cards'])}")
        if death.get("add_labs"):
            lines.append(f"- Priority labs: {', '.join(death['add_labs'])}")

    presets = blueprint.get("presets") or {}
    for context_id, context in presets.items():
        cards = context.get("cards") or {}
        modules = context.get("modules") or {}
        lines.extend(["", f"## {cards.get('label', context_id.title())}"])
        if cards.get("note"):
            lines.append(cards["note"])
        lines.append("")
        lines.append("### Cards to equip")
        for card in cards.get("recommended") or []:
            lines.append(f"- {card}")
        lines.append("")
        lines.append("### Modules")
        for row in modules.get("rows") or []:
            lines.append(
                f"- {row.get('slot')}: equip **{row.get('recommended')}** "
                f"(currently {row.get('equipped')}, {row.get('status')})"
            )

    substats = blueprint.get("substats") or {}
    lines.extend(["", "## Sub-effect reroll targets"])
    for row in substats.get("rows") or []:
        lines.append(f"- {row.get('Slot')} · {row.get('Target')}: {row.get('Current')} → {row.get('Goal')} ({row.get('Status')})")

    for section_key, title, columns in (
        ("bots", "## Bots", ("Bot", "Priority", "Target", "Current", "Status")),
        ("guardians", "## Guardians", ("Guardian", "Priority", "Target", "Current", "Status")),
        ("masteries", "## Card masteries", ("Card", "Level", "Mastery", "Target", "Status")),
        ("vault", "## Vault", ("Vault node", "Progress", "Status")),
    ):
        section = beast.get(section_key) or {}
        lines.append("")
        lines.extend(_lines(title, section.get("rows") or [], columns))

    uw = beast.get("ultimate_weapons") or {}
    lines.extend(["", "## Ultimate Weapons"])
    for note in uw.get("notes") or []:
        lines.append(f"- {note}")
    lines.extend(_lines("", uw.get("rows") or [], ("Ultimate Weapon", "Owned", "Status", "Notes")))

    lines.extend(["", "## Research priority"])
    research = blueprint.get("research") or {}
    lines.extend(_lines("### Labs", research.get("labs") or [], ("Priority", "Research", "Current", "Status")))
    lines.extend(_lines("### Workshop", research.get("workshop") or [], ("Priority", "Research", "Current", "Status")))

    lines.extend(["", "---", "Generated by Tower Optimizer Beast Mode"])
    return "\n".join(lines)


def format_playbook_plaintext(report: Mapping[str, Any], *, profile_name: str = "") -> str:
    markdown = format_playbook_markdown(report, profile_name=profile_name)
    return (
        markdown.replace("# ", "")
        .replace("## ", "")
        .replace("### ", "")
        .replace("**", "")
    )


def build_playbook_html(report: Mapping[str, Any], *, profile_name: str = "") -> str:
    markdown = format_playbook_markdown(report, profile_name=profile_name)
    body_lines = []
    for line in markdown.splitlines():
        safe = escape(line)
        if line.startswith("# "):
            body_lines.append(f"<h1>{escape(line[2:])}</h1>")
        elif line.startswith("## "):
            body_lines.append(f"<h2>{escape(line[3:])}</h2>")
        elif line.startswith("### "):
            body_lines.append(f"<h3>{escape(line[4:])}</h3>")
        elif line.startswith("- "):
            body_lines.append(f"<li>{escape(line[2:].replace('**', ''))}</li>")
        elif line.startswith("  - "):
            body_lines.append(f"<li class='indent'>{escape(line[4:])}</li>")
        elif not line.strip():
            body_lines.append("<br>")
        else:
            body_lines.append(f"<p>{safe}</p>")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Beast Mode Playbook — {escape(str(report.get('label', 'Build')))}</title>
  <style>
    body {{ font-family: Segoe UI, Arial, sans-serif; max-width: 920px; margin: 2rem auto; color: #111; line-height: 1.45; }}
    h1, h2, h3 {{ color: #0b3954; }}
    li {{ margin: 0.25rem 0; }}
    li.indent {{ margin-left: 1rem; }}
    @media print {{ body {{ margin: 0.75in; }} }}
  </style>
</head>
<body>
{''.join(body_lines)}
</body>
</html>"""


def build_playbook_pdf_bytes(report: Mapping[str, Any], *, profile_name: str = "") -> bytes:
    try:
        from fpdf import FPDF
    except ImportError as exc:
        raise RuntimeError("PDF export requires fpdf2. Install requirements.txt and rebuild the container.") from exc

    text = format_playbook_plaintext(report, profile_name=profile_name)
    pdf = FPDF()
    pdf.set_margins(12, 12, 12)
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()
    pdf.set_font("Helvetica", size=9)
    line_width = pdf.w - pdf.l_margin - pdf.r_margin
    for line in text.splitlines():
        safe = _ascii_safe(line).replace("\t", " ")
        if not safe.strip():
            pdf.ln(3)
            continue
        chunks = wrap(safe, width=105) or [safe]
        for chunk in chunks:
            pdf.multi_cell(line_width, 4, chunk)
    buffer = BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()


def playbook_export_bundle(report: Mapping[str, Any], *, profile_name: str = "") -> Dict[str, Any]:
    label = str(report.get("label") or "build").lower().replace(" ", "-")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    base = f"beast-mode-{label}-{stamp}"
    bundle: Dict[str, Any] = {
        "markdown": format_playbook_markdown(report, profile_name=profile_name),
        "plaintext": format_playbook_plaintext(report, profile_name=profile_name),
        "html": build_playbook_html(report, profile_name=profile_name),
        "filenames": {
            "markdown": f"{base}.md",
            "plaintext": f"{base}.txt",
            "html": f"{base}.html",
            "pdf": f"{base}.pdf",
        },
    }
    try:
        bundle["pdf"] = build_playbook_pdf_bytes(report, profile_name=profile_name)
    except RuntimeError as exc:
        bundle["pdf"] = None
        bundle["pdf_error"] = str(exc)
    return bundle
